x-environment: &environment
  DEBUG: 1

x-logging-options: &logging
  options:
    max-size: "10m"
    max-file: "2"

services:
  ci:
    build:
      context: .
      dockerfile: ci/Dockerfile
    image: ${REG}/ci/${SRV}:${CI}
    environment:
      - WEB_CONCURRENCY=1  # works only without --reload
    logging:
      <<: *logging
    volumes:
      - ./src:/srv
    command: bash

networks:
  default:
    external: true
    name: rt_default