x-environment: &environment
  DEBUG: 1

x-logging-options: &logging
  options:
    max-size: "10m"
    max-file: "2"

services:
  ci:
    build:
      context: .
      dockerfile: ci/Dockerfile
    image: ${REG}/ci/${SRV}:${CI}
    environment:
      - WEB_CONCURRENCY=1  # works only without --reload
    logging:
      <<: *logging
    ports:
      - 8000:80
    volumes:
      - ./src:/srv
    command: fastapi dev main.py --port 80 --host 0.0.0.0 --reload

networks:
  default:
    external: true
    name: rt_default